version: '3'

services: 
    nginx:
        image: nginx:latest
        container_name: nginx
        ports: 
            - "80:80"
            - "443:443"
        links: 
            - php-fpm

    php-fpm:
        image: php:fpm-buster
        container_name: php-fpm
        ports: 
            - "9000"

    mysql:
        image: mariadb:latest
        container_name: mysql
        ports: 
            - "8002:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=app
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=password