version: '3'

services: 
    nginx:
        image: nginx:latest
        container_name: nginx
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./app:/var/www/html/:cached
            - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./config/nginx/nginx_conf:/etc/nginx/nginx_conf
        links: 
            - php-fpm

    php-fpm:
        image: php:7.4-fpm-buster
        container_name: php-fpm
        working_dir: /var/www/html
        ports: 
            - "9000"
        volumes: 
            - ./app:/var/www/html/:cached
            - ./config/php/php.ini:/usr/local/etc/php/php.ini

    mysql:
        image: mariadb:latest
        container_name: mysql
        ports: 
            - "8002:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=app
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=password